// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['app']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ListTasks() {
  return window['go']['app']['App']['ListTasks']();
}

export function RecentRuns(arg1) {
  return window['go']['app']['App']['RecentRuns'](arg1);
}

export function RunTask(arg1) {
  return window['go']['app']['App']['RunTask'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SelectDirectoryPath() {
  return window['go']['app']['App']['SelectDirectoryPath']();
}

export function SelectFilePath() {
  return window['go']['app']['App']['SelectFilePath']();
}

export function UpdateTask(arg1, arg2) {
  return window['go']['app']['App']['UpdateTask'](arg1, arg2);
}
