// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {config} from '../models';

export function CreateTask(arg1:task.Task):Promise<task.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function ListTasks():Promise<Array<task.Task>>;

export function RecentRuns(arg1:number):Promise<Array<task.RunRecord>>;

export function RunTask(arg1:string):Promise<task.RunRecord>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function UpdateTask(arg1:string,arg2:task.Task):Promise<task.Task>;
